# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled  e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective Eng. Nevil
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/Technician-Nevil e.g., npm/babel
community_bridge: # Replace with a single Community Bridge ACWICT-College e.g., cloud-foundry
liberapay: # Replace with a single Liberapay ZITECH
issuehunt: # Replace with a single IssueHunt UN
otechie: # Replace with a single Otechie Nevil-Okoth 
lfx_crowdfunding: # Replace with a single LFX Crowdfunding Technician-Nevil e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship nevil696/technician-nevil/ e.g., ['link1', 'link2']
